local Fusion = require "./Packages/Fusion"

-- local Event = Fusion.Event
-- local Children

-- local Button = require "@self/Components/Button"
-- local Div = require "@self/Components/Div"

return function(scope: Fusion.Scope<typeof(Fusion)>)
	-- local topbar = Div(scope, {
	-- 	native = {
	-- 		Size = UDim2.fromScale(1, 0.15),
	--         AnchorPoint = Vector2.new(0.5, 0),
	-- 	},
	-- })
	-- local body = Div(scope, {
	-- 	native = {
	-- 		Size = UDim2.fromScale(1, 0.85),
	--         AnchorPoint = Vector2.new(0.5, 0),
	--         Position =
	-- 	},
	-- })

	-- return body
end
